### ISSUE TITLE
Touch screen disabled when win mag is enabled

### ISSUE THREAD

**Issue by ChrisMedley** [CyrilleB79/winMag#1] opened 2020-02-21 19:16 UTC
Running NVDA 2019.3.1
With windows magnifier 1.0 dev 20200218

With the add-on enabled my touch screen on my laptop no longer responds to touch but with the add-on disabled touch is working again

**Comment by CyrilleB79** [comment] 2020-02-21 23:02
I do not know anything on touch screen and do not have such a device. So I will have to find a way to investigate it...

Could you provide 2 logs (debug level) when you execute the same simple touch action, one log with Windows Magnifier add-on enabled and the second one with this add-on disabled. Maybe I can find something interesting.

Another idea:
If you enter input help mode (NVDA+1) and execute a simple touch action, what is the result with and witouht winmag enabled?

**Comment by ChrisMedley** [comment] 2020-02-22 08:24
Ok I added two logs with the win mag enabled and disabled

With win mag enabled and input help on still no response from touch
[win mag - enabled.txt](https://github.com/CyrilleB79/winMag/files/4238998/win.mag.-.enabled.txt)
[win mag -disabled.txt](https://github.com/CyrilleB79/winMag/files/4238999/win.mag.-disabled.txt)

**Comment by CyrilleB79** [comment] 2020-02-22 22:49
Thanks for the logs.
Can you explain what differs from the 2 experiences?
What gesture do you make and what is the differing result with winmag add-on enabled or not?

Another check to do would be to disable all your add-ons but Winmag to ensure the issue is not an incompatibility between 2 add-ons.

Thanks.

**Comment by ChrisMedley** [comment] 2020-02-23 09:26
After disabling all add-ons except win mag enabled only there is still no touch screen response at all but with win mag disabled touch is working again , so this must be an issue with win mag add-on itself as it still disables touch screen functionality when it is enabled on its own with no other add-ons enabled



the logs above were with a simple one finger touch on a text document

with  win mag enabled there is no feedback of text in the document

with win mag disabled the same one finger touch reads the document text okay

**Comment by CyrilleB79** [comment] 2020-02-24 15:05
@ChrisMedley, I have fixed an issue on braille routing key. This fix may also impact touchscreen inpu gestures as well as any other input gesture that is not a keyboard input gesture.

Could you please try the following release: [winMag-1.0-dev-20200224.nvda-addon](https://github.com/CyrilleB79/winMag/releases/download/V1.0-dev-20200224/winMag-1.0-dev-20200224.nvda-addon)

In case the issue is not fixed, could you provide 2 logs (debug level) when you execute the same simple touch action, one log with Windows Magnifier add-on enabled and the second one with this add-on disabled?
Indeed, the logs that you have previously provided are both with winmag add-on disabled. In fact the content of both files is identical.

**Comment by ChrisMedley** [comment] 2020-02-24 15:32
OK, that seems to have fixed the touch screen issue as well, all seems to be working as it should now, thank you

Apologies for the mix up with the previous logs, I don't know what happens there , but again thank you for the fix.


Keep up the great work.

**Comment by CyrilleB79** [comment] 2020-02-29 10:16
Fixed in commit 73c560ef45209db7a157440f34a3c516283d10eb. And released in V1.0-dev-20200224.

**Closed by CyrilleB79** 2020-02-29 10:16 UTC
