### ISSUE TITLE
With some text opened in a text editor, Control+Alt+ArrowKeys causes screen to freeze

### ISSUE THREAD

**Issue by k-kolev1985** [CyrilleB79/winMag#2] opened 2020-02-27 13:53 UTC
### Steps to reproduce:
1. Install the latest development build of the "Windows Magnifier" NVDA add-on.
2. Open a text editor (the built-in Notepad will do) and type some text in it or open a file containing some text.
3. Select some text in the text editor (even just one selected word will do). Actually, now that I've tested more, it seams that text selection is not a requirement for reproducing the issue.
4. Activate the Windows Magnifier by pressing Windows+NumPadPlus.
5. Use the Control+Alt+Left/Right/Up/Down combination to move the magnified view around (hold it for a few seconds).

### Actual behavior:
When the Control+Alt+Left/Right/Up/Down combination is executed for a few seconds, the screen view will freeze until NVDA is restarted.

### Expected behavior:
When the Control+Alt+Left/Right/Up/Down combination is executed for a few seconds, the screen view should not freeze.

### System configuration
- Operating system: Windows 10 Pro version 1909 (build 18363.657), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-19724,2c4caa62, in bulgarian.
- "Windows Magnifier" add-on version: 1.0-dev-20200225.
- Processor: Intel Core i5-9400F at 2.90GHz.
- RAM Memory: 16.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

#### Does the issue still occur after restarting your PC?
Yes, it does.

#### Have you tried any other versions of NVDA or the add-on? If so, please report their behaviors:
I haven't tested with older versions of NVDA. The problem was occurring with build 1.0-dev-20200218.

**Comment by CyrilleB79** [comment] 2021-02-03 22:40
@k-kolev1985, I could reproduce this issue in the past; that was the reason why I did not perform a stable release.
However I cannot reproduce it anymore; I cannot remember since when.
Are you still able to reproduce it? If yes, which is your config info (WinMag, NVDA and Windows versions) ?
Thanks.

**Comment by k-kolev1985** [comment] 2021-02-04 10:01
@CyrilleB79 Mainly due to this issue, I haven't used the add-on in quite some time and it was disabled. I've reenabled it now and I've tested it again. The issue did not occur. The version of the add-on is a bit newer than the one with which I've tested before (now it is 1.0-dev-20200306), but if I remember correctly, I was able to reproduce the issue with this newer version as well. Maybe the fault for the issue was complex - partly due to the add-on, but also partly due to other components (e.g. NVDA, Windows, etc.). The versions of both NVDA and Windows have changed since I last tested the add-on, so who knows... 😊 I'll keep the add-on enabled and observe if the issue will occur again.

**Comment by CyrilleB79** [comment] 2021-06-15 07:40
Since this issue cannot be reproduced anymore with recente releases, especially [1.0](https://github.com/CyrilleB79/winMag/releases/download/V1.0/winMag-1.0.nvda-addon), I will close this issue.
Feel free to re-open it or another one if the issue comes back.

**Closed by CyrilleB79** 2021-06-15 07:40 UTC
